<?php declare(strict_types=1);

namespace Citrus\Contracts;

interface HttpResponseHeaders
{

    const RESPONSE_HEADERS = [
        'Accept-CH',
        'Accept-CH-Lifetime',
        'Accept-Patch',
        'Accept-Ranges',
        'Access-Control-Allow-Origin',
        'Access-Control-Allow-Credentials',
        'Access-Control-Expose-Headers',
        'Access-Control-Max-Age',
        'Access-Control-Allow-Methods',
        'Access-Control-Allow-Headers',
        'Alt-Svc',
        'Age',
        'Allow',
        'Alt-Svc',
        'Cache-Control',
        'Clear-Site-Data',
        'Connection',
        'Content-Disposition',
        'Content-Encoding',
        'Content-Language',
        'Content-Length',
        'Content-Location',
        'Content-MD5',
        'Content-Range',
        'Content-Security-Policy',
        'Content-Type',
        'Cross-Origin-Embedder-Policy',
        'Cross-Origin-Opener-Policy',
        'Cross-Origin-Resource-Policy',
        'Cross-Origin-Resource-Policy',
        'Content-Security-Policy',
        'Content-Security-Policy-Report-Only',
        'Date',
        'Delta-Base',
        'ETag',
        'Expect-CT',
        'Expires',
        'Feature-Policy',
        'IM',
        'Last-Modified',
        'Link',
        'Location',
        'NEL',
        'P3P',
        'Permissions-Policy',
        'Pragma',
        'Preference-Applied',
        'Proxy-Authenticate',
        'Public-Key-Pins',
        'Refresh',
        'Report-To',
        'Retry-After',
        'Server',
        'Set-Cookie',
        'Status',
        'Strict-Transport-Security',
        'Timing-Allow-Origin',
        'Tk',
        'Trailer',
        'Transfer-Encoding',
        'Upgrade',
        'Vary',
        'Via',
        'WWW-Authenticate',
        'Warning',
        'X-Content-Duration',
        'X-Content-Type-Options',
        'X-Frame-Options',
        'X-Powered-By',
        'X-Redirect-By',
        'X-UA-Compatible',
        'X-XSS-Protection',
        'X-Content-Security-Policy',
        'X-WebKit-CSP'
    ];

}
